### ISSUE TITLE
Asset build fails out of the box

### ISSUE THREAD

**Issue by mriede** [angel-example/explode#2]
Hi! I've cloned this repo, ran pub get and the build fails while running `pub get`. I haven't made any changes to the source code.

Angel looks fun and promising, but if you provide examples, at least make sure they're working.

```
Loading source assets... 
Loading dart_to_js_script_rewriter transformers... 
Building explode... 
[Info from Dart2JS]:
Compiling explode|web/main.dart...
[Error from Dart2JS on explode|web/main.dart]:
web/packages/explode/src/models/user.dart:6:1:
Can't read 'package:explode/src/models/user.g.dart' (Could not find asset explode|lib/src/models/user.g.dart.).
part 'user.g.dart';
^^^^^^^^^^^^^^^^^^^
[Warning from Dart2JS]:
web/main.dart:14:3:
Cannot resolve type 'WebSocketsService'.
  WebSocketsService bombService = app.service('bombs'),
  ^^^^^^^^^^^^^^^^^
[Info from Dart2JS]:
Took 0:00:06.178164 to compile explode|web/main.dart.
Build failed.
```

**Comment by thosakwe** [comment]
Hey! Thanks for the feedback.

To be fair, this tutorial was quite outdated. It was from when Angel was still in beta; now we're at `1.1.0`, the second major release.

I've just finished upgrading the project to use the latest versions.
